require "json"
require "yaml"
require "fileutils"

CONTENT = File.dirname __FILE__
BUILD = File.join CONTENT, "_build"
FileUtils.mkdir_p BUILD

def content_data(path)
  YAML.load_file(path).tap do |data|
    data["content"] = File.read(path).split("---")[2..-1].join("---").strip
  end
end

task default: [:dashboard, :lessons, :info]

task :dashboard do
  YAML.load_file(File.join(CONTENT, "_data", "projects.yaml")).tap do |projects|
    output = File.join BUILD, "dashboard"
    data = {
      projects: projects.map do |project|
        {
          title: project["title"],
          slug: project["slug"],
          lessons: project["lessons"].map do |lesson|
            lesson.select { |key, _| key =~ /title|location/ }
          end,
        }
      end
    }
    File.write output, data.to_json
  end
end

task :lessons do
  YAML.load_file(File.join(CONTENT, "_data", "projects.yaml")).each do |project|
    output = File.join BUILD, "lessons"
    project["lessons"].each do |config|
      data = {
        title: config["title"],
        items: config["items"].map do |item|
          content_data File.join CONTENT, config["location"], "#{item}.md"
        end
      }
      File.write File.join(output, config["location"]), data.to_json
    end
  end
end

task :info do
  Dir.glob(File.join(CONTENT, "*.md")) do |path|
    destination = File.join BUILD, File.basename(path, ".md")
    File.write destination, content_data(path).to_json
  end
end
